/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AppointmentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Time = IDL.Int;
export const Appointment = IDL.Record({
  'id' : IDL.Text,
  'status' : AppointmentStatus,
  'serviceType' : IDL.Text,
  'clientId' : IDL.Opt(IDL.Text),
  'associatedUser' : IDL.Principal,
  'clientName' : IDL.Text,
  'dateTime' : Time,
});
export const Client = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const InvoiceStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'overdue' : IDL.Null,
});
export const Invoice = IDL.Record({
  'id' : IDL.Text,
  'status' : InvoiceStatus,
  'clientId' : IDL.Text,
  'owner' : IDL.Principal,
  'dueDate' : Time,
  'workDescription' : IDL.Text,
  'amount' : IDL.Nat,
});
export const InvoiceReminder = IDL.Record({
  'id' : IDL.Text,
  'userId' : IDL.Principal,
  'dueDate' : Time,
  'invoiceId' : IDL.Text,
  'reminderTime' : Time,
  'message' : IDL.Text,
});
export const MailSender = IDL.Record({
  'displayName' : IDL.Text,
  'address' : IDL.Text,
});
export const MailNotification = IDL.Record({
  'id' : IDL.Text,
  'subject' : IDL.Text,
  'source' : IDL.Text,
  'read' : IDL.Bool,
  'user' : IDL.Principal,
  'sender' : MailSender,
  'timestamp' : Time,
});
export const Meeting = IDL.Record({
  'id' : IDL.Text,
  'startTime' : Time,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'participants' : IDL.Vec(IDL.Principal),
  'clientId' : IDL.Opt(IDL.Text),
  'endTime' : Time,
  'description' : IDL.Text,
});
export const NotificationType = IDL.Variant({
  'reminder' : IDL.Null,
  'mail' : IDL.Null,
  'message' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'notificationType' : NotificationType,
  'read' : IDL.Bool,
  'user' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : Time,
  'mailNotification' : IDL.Opt(MailNotification),
});
export const Reminder = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Principal,
  'time' : Time,
  'message' : IDL.Text,
});
export const Priority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'clientId' : IDL.Opt(IDL.Text),
  'owner' : IDL.Principal,
  'completed' : IDL.Bool,
  'dueDate' : Time,
  'description' : IDL.Text,
  'priority' : Priority,
});
export const AutomationAction = IDL.Variant({
  'createNotification' : Notification,
  'createTask' : Task,
  'createMeeting' : Meeting,
  'createAppointment' : Appointment,
  'createReminder' : Reminder,
});
export const AutomationTrigger = IDL.Variant({
  'taskCompleted' : IDL.Text,
  'meetingEnded' : IDL.Text,
  'clientCreated' : IDL.Text,
});
export const WorkflowAutomationRule = IDL.Record({
  'id' : IDL.Text,
  'action' : AutomationAction,
  'trigger' : AutomationTrigger,
  'enabled' : IDL.Bool,
});
export const ChatGroup = IDL.Record({
  'id' : IDL.Text,
  'creator' : IDL.Principal,
  'members' : IDL.Vec(IDL.Principal),
});
export const KanbanColumn = IDL.Record({
  'name' : IDL.Text,
  'taskOrder' : IDL.Vec(IDL.Text),
});
export const KanbanBoard = IDL.Record({
  'layout' : IDL.Vec(IDL.Text),
  'columns' : IDL.Vec(KanbanColumn),
});
export const Message = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'department' : IDL.Text,
});
export const AutomationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
  'failed' : IDL.Null,
});
export const AutomationEvent = IDL.Record({
  'id' : IDL.Text,
  'action' : IDL.Text,
  'trigger' : AutomationTrigger,
  'timestamp' : Time,
});
export const WorkflowAutomationLogEntry = IDL.Record({
  'id' : IDL.Text,
  'status' : AutomationStatus,
  'ruleId' : IDL.Text,
  'user' : IDL.Principal,
  'event' : AutomationEvent,
  'timestamp' : Time,
});
export const EntityCount = IDL.Record({
  'automationLogs' : IDL.Nat,
  'tasks' : IDL.Nat,
  'notifications' : IDL.Nat,
  'meetings' : IDL.Nat,
  'messages' : IDL.Nat,
  'userProfiles' : IDL.Nat,
  'appointments' : IDL.Nat,
  'invoices' : IDL.Nat,
  'invoiceReminders' : IDL.Nat,
  'kanbanBoards' : IDL.Nat,
  'reminders' : IDL.Nat,
  'chatGroups' : IDL.Nat,
  'mailNotifications' : IDL.Nat,
  'clients' : IDL.Nat,
  'workflowRules' : IDL.Nat,
});
export const ProductivitySummary = IDL.Record({
  'overdueTasks' : IDL.Nat,
  'activeMeetings' : IDL.Nat,
  'availableSlots' : IDL.Nat,
  'upcomingReminders' : IDL.Nat,
});
export const SchedulingSuggestions = IDL.Record({
  'scheduleResolutions' : IDL.Text,
  'availableTimeBlocks' : IDL.Vec(Time),
  'suggestedMeetings' : IDL.Vec(Meeting),
});

export const idlService = IDL.Service({
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAppointment' : IDL.Func([Appointment], [], []),
  'createChatGroup' : IDL.Func([IDL.Text, IDL.Vec(IDL.Principal)], [], []),
  'createClient' : IDL.Func([Client], [], []),
  'createInvoice' : IDL.Func([Invoice], [], []),
  'createInvoiceReminder' : IDL.Func([InvoiceReminder], [], []),
  'createMailNotification' : IDL.Func([MailNotification], [], []),
  'createMeeting' : IDL.Func([Meeting], [], []),
  'createNotification' : IDL.Func([Notification], [], []),
  'createReminder' : IDL.Func([Reminder], [], []),
  'createTask' : IDL.Func([Task], [], []),
  'createWorkflowRule' : IDL.Func([WorkflowAutomationRule], [], []),
  'deleteAppointment' : IDL.Func([IDL.Text], [], []),
  'deleteClient' : IDL.Func([IDL.Text], [], []),
  'deleteInvoice' : IDL.Func([IDL.Text], [], []),
  'deleteInvoiceReminder' : IDL.Func([IDL.Text], [], []),
  'deleteMailNotification' : IDL.Func([IDL.Text], [], []),
  'deleteMeeting' : IDL.Func([IDL.Text], [], []),
  'deleteNotification' : IDL.Func([IDL.Text], [], []),
  'deleteReminder' : IDL.Func([IDL.Text], [], []),
  'deleteTask' : IDL.Func([IDL.Text], [], []),
  'deleteWorkflowRule' : IDL.Func([IDL.Text], [], []),
  'getAdminAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getAdminAllChatGroups' : IDL.Func([], [IDL.Vec(ChatGroup)], ['query']),
  'getAdminAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'getAdminAllInvoiceReminders' : IDL.Func(
      [],
      [IDL.Vec(InvoiceReminder)],
      ['query'],
    ),
  'getAdminAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getAdminAllKanbanBoards' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, KanbanBoard))],
      ['query'],
    ),
  'getAdminAllMailNotifications' : IDL.Func(
      [],
      [IDL.Vec(MailNotification)],
      ['query'],
    ),
  'getAdminAllMeetings' : IDL.Func([], [IDL.Vec(Meeting)], ['query']),
  'getAdminAllMessages' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(Message)))],
      ['query'],
    ),
  'getAdminAllNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getAdminAllReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
  'getAdminAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getAdminAllUserProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getAdminAllWorkflowLogs' : IDL.Func(
      [],
      [IDL.Vec(WorkflowAutomationLogEntry)],
      ['query'],
    ),
  'getAdminAllWorkflowRules' : IDL.Func(
      [],
      [IDL.Vec(WorkflowAutomationRule)],
      ['query'],
    ),
  'getAdminDueReminders' : IDL.Func([Time], [IDL.Vec(Reminder)], ['query']),
  'getAdminEntityCounts' : IDL.Func([], [EntityCount], ['query']),
  'getAdminPendingInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getAdminTasksByCompletion' : IDL.Func(
      [IDL.Bool],
      [IDL.Vec(Task)],
      ['query'],
    ),
  'getAdminTasksByPriority' : IDL.Func([Priority], [IDL.Vec(Task)], ['query']),
  'getAdminUnpaidInvoiceReminders' : IDL.Func(
      [],
      [IDL.Vec(InvoiceReminder)],
      ['query'],
    ),
  'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getAllMeetings' : IDL.Func([], [IDL.Vec(Meeting)], ['query']),
  'getAllReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getAllWorkflowRules' : IDL.Func(
      [],
      [IDL.Vec(WorkflowAutomationRule)],
      ['query'],
    ),
  'getAppointment' : IDL.Func([IDL.Text], [Appointment], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatGroups' : IDL.Func([], [IDL.Vec(ChatGroup)], ['query']),
  'getClient' : IDL.Func([IDL.Text], [Client], ['query']),
  'getInvoice' : IDL.Func([IDL.Text], [Invoice], ['query']),
  'getInvoiceReminders' : IDL.Func([], [IDL.Vec(InvoiceReminder)], ['query']),
  'getKanbanBoard' : IDL.Func([], [KanbanBoard], ['query']),
  'getMailNotifications' : IDL.Func([], [IDL.Vec(MailNotification)], ['query']),
  'getMeeting' : IDL.Func([IDL.Text], [Meeting], ['query']),
  'getMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getProductivitySummary' : IDL.Func([], [ProductivitySummary], ['query']),
  'getReminder' : IDL.Func([IDL.Text], [Reminder], ['query']),
  'getSchedulingSuggestions' : IDL.Func([], [SchedulingSuggestions], ['query']),
  'getTask' : IDL.Func([IDL.Text], [Task], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkflowAutomationLogs' : IDL.Func(
      [],
      [IDL.Vec(WorkflowAutomationLogEntry)],
      ['query'],
    ),
  'getWorkflowRule' : IDL.Func([IDL.Text], [WorkflowAutomationRule], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isDatabaseAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logWorkflowAutomation' : IDL.Func([WorkflowAutomationLogEntry], [], []),
  'markMailAsRead' : IDL.Func([IDL.Text], [], []),
  'markNotificationAsRead' : IDL.Func([IDL.Text], [], []),
  'recordInvoicePayment' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Text, Message], [], []),
  'updateAppointment' : IDL.Func([IDL.Text, Appointment], [], []),
  'updateClient' : IDL.Func([IDL.Text, Client], [], []),
  'updateInvoice' : IDL.Func([IDL.Text, Invoice], [], []),
  'updateKanbanBoard' : IDL.Func([KanbanBoard], [], []),
  'updateMeeting' : IDL.Func([IDL.Text, Meeting], [], []),
  'updateReminder' : IDL.Func([IDL.Text, Reminder], [], []),
  'updateTask' : IDL.Func([IDL.Text, Task], [], []),
  'updateWorkflowRule' : IDL.Func([IDL.Text, WorkflowAutomationRule], [], []),
  'validateDatabaseAccess' : IDL.Func([], [], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AppointmentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Time = IDL.Int;
  const Appointment = IDL.Record({
    'id' : IDL.Text,
    'status' : AppointmentStatus,
    'serviceType' : IDL.Text,
    'clientId' : IDL.Opt(IDL.Text),
    'associatedUser' : IDL.Principal,
    'clientName' : IDL.Text,
    'dateTime' : Time,
  });
  const Client = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const InvoiceStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'overdue' : IDL.Null,
  });
  const Invoice = IDL.Record({
    'id' : IDL.Text,
    'status' : InvoiceStatus,
    'clientId' : IDL.Text,
    'owner' : IDL.Principal,
    'dueDate' : Time,
    'workDescription' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const InvoiceReminder = IDL.Record({
    'id' : IDL.Text,
    'userId' : IDL.Principal,
    'dueDate' : Time,
    'invoiceId' : IDL.Text,
    'reminderTime' : Time,
    'message' : IDL.Text,
  });
  const MailSender = IDL.Record({
    'displayName' : IDL.Text,
    'address' : IDL.Text,
  });
  const MailNotification = IDL.Record({
    'id' : IDL.Text,
    'subject' : IDL.Text,
    'source' : IDL.Text,
    'read' : IDL.Bool,
    'user' : IDL.Principal,
    'sender' : MailSender,
    'timestamp' : Time,
  });
  const Meeting = IDL.Record({
    'id' : IDL.Text,
    'startTime' : Time,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'participants' : IDL.Vec(IDL.Principal),
    'clientId' : IDL.Opt(IDL.Text),
    'endTime' : Time,
    'description' : IDL.Text,
  });
  const NotificationType = IDL.Variant({
    'reminder' : IDL.Null,
    'mail' : IDL.Null,
    'message' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'notificationType' : NotificationType,
    'read' : IDL.Bool,
    'user' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : Time,
    'mailNotification' : IDL.Opt(MailNotification),
  });
  const Reminder = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Principal,
    'time' : Time,
    'message' : IDL.Text,
  });
  const Priority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'clientId' : IDL.Opt(IDL.Text),
    'owner' : IDL.Principal,
    'completed' : IDL.Bool,
    'dueDate' : Time,
    'description' : IDL.Text,
    'priority' : Priority,
  });
  const AutomationAction = IDL.Variant({
    'createNotification' : Notification,
    'createTask' : Task,
    'createMeeting' : Meeting,
    'createAppointment' : Appointment,
    'createReminder' : Reminder,
  });
  const AutomationTrigger = IDL.Variant({
    'taskCompleted' : IDL.Text,
    'meetingEnded' : IDL.Text,
    'clientCreated' : IDL.Text,
  });
  const WorkflowAutomationRule = IDL.Record({
    'id' : IDL.Text,
    'action' : AutomationAction,
    'trigger' : AutomationTrigger,
    'enabled' : IDL.Bool,
  });
  const ChatGroup = IDL.Record({
    'id' : IDL.Text,
    'creator' : IDL.Principal,
    'members' : IDL.Vec(IDL.Principal),
  });
  const KanbanColumn = IDL.Record({
    'name' : IDL.Text,
    'taskOrder' : IDL.Vec(IDL.Text),
  });
  const KanbanBoard = IDL.Record({
    'layout' : IDL.Vec(IDL.Text),
    'columns' : IDL.Vec(KanbanColumn),
  });
  const Message = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'department' : IDL.Text,
  });
  const AutomationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
    'failed' : IDL.Null,
  });
  const AutomationEvent = IDL.Record({
    'id' : IDL.Text,
    'action' : IDL.Text,
    'trigger' : AutomationTrigger,
    'timestamp' : Time,
  });
  const WorkflowAutomationLogEntry = IDL.Record({
    'id' : IDL.Text,
    'status' : AutomationStatus,
    'ruleId' : IDL.Text,
    'user' : IDL.Principal,
    'event' : AutomationEvent,
    'timestamp' : Time,
  });
  const EntityCount = IDL.Record({
    'automationLogs' : IDL.Nat,
    'tasks' : IDL.Nat,
    'notifications' : IDL.Nat,
    'meetings' : IDL.Nat,
    'messages' : IDL.Nat,
    'userProfiles' : IDL.Nat,
    'appointments' : IDL.Nat,
    'invoices' : IDL.Nat,
    'invoiceReminders' : IDL.Nat,
    'kanbanBoards' : IDL.Nat,
    'reminders' : IDL.Nat,
    'chatGroups' : IDL.Nat,
    'mailNotifications' : IDL.Nat,
    'clients' : IDL.Nat,
    'workflowRules' : IDL.Nat,
  });
  const ProductivitySummary = IDL.Record({
    'overdueTasks' : IDL.Nat,
    'activeMeetings' : IDL.Nat,
    'availableSlots' : IDL.Nat,
    'upcomingReminders' : IDL.Nat,
  });
  const SchedulingSuggestions = IDL.Record({
    'scheduleResolutions' : IDL.Text,
    'availableTimeBlocks' : IDL.Vec(Time),
    'suggestedMeetings' : IDL.Vec(Meeting),
  });
  
  return IDL.Service({
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAppointment' : IDL.Func([Appointment], [], []),
    'createChatGroup' : IDL.Func([IDL.Text, IDL.Vec(IDL.Principal)], [], []),
    'createClient' : IDL.Func([Client], [], []),
    'createInvoice' : IDL.Func([Invoice], [], []),
    'createInvoiceReminder' : IDL.Func([InvoiceReminder], [], []),
    'createMailNotification' : IDL.Func([MailNotification], [], []),
    'createMeeting' : IDL.Func([Meeting], [], []),
    'createNotification' : IDL.Func([Notification], [], []),
    'createReminder' : IDL.Func([Reminder], [], []),
    'createTask' : IDL.Func([Task], [], []),
    'createWorkflowRule' : IDL.Func([WorkflowAutomationRule], [], []),
    'deleteAppointment' : IDL.Func([IDL.Text], [], []),
    'deleteClient' : IDL.Func([IDL.Text], [], []),
    'deleteInvoice' : IDL.Func([IDL.Text], [], []),
    'deleteInvoiceReminder' : IDL.Func([IDL.Text], [], []),
    'deleteMailNotification' : IDL.Func([IDL.Text], [], []),
    'deleteMeeting' : IDL.Func([IDL.Text], [], []),
    'deleteNotification' : IDL.Func([IDL.Text], [], []),
    'deleteReminder' : IDL.Func([IDL.Text], [], []),
    'deleteTask' : IDL.Func([IDL.Text], [], []),
    'deleteWorkflowRule' : IDL.Func([IDL.Text], [], []),
    'getAdminAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getAdminAllChatGroups' : IDL.Func([], [IDL.Vec(ChatGroup)], ['query']),
    'getAdminAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'getAdminAllInvoiceReminders' : IDL.Func(
        [],
        [IDL.Vec(InvoiceReminder)],
        ['query'],
      ),
    'getAdminAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getAdminAllKanbanBoards' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, KanbanBoard))],
        ['query'],
      ),
    'getAdminAllMailNotifications' : IDL.Func(
        [],
        [IDL.Vec(MailNotification)],
        ['query'],
      ),
    'getAdminAllMeetings' : IDL.Func([], [IDL.Vec(Meeting)], ['query']),
    'getAdminAllMessages' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(Message)))],
        ['query'],
      ),
    'getAdminAllNotifications' : IDL.Func(
        [],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getAdminAllReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
    'getAdminAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getAdminAllUserProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getAdminAllWorkflowLogs' : IDL.Func(
        [],
        [IDL.Vec(WorkflowAutomationLogEntry)],
        ['query'],
      ),
    'getAdminAllWorkflowRules' : IDL.Func(
        [],
        [IDL.Vec(WorkflowAutomationRule)],
        ['query'],
      ),
    'getAdminDueReminders' : IDL.Func([Time], [IDL.Vec(Reminder)], ['query']),
    'getAdminEntityCounts' : IDL.Func([], [EntityCount], ['query']),
    'getAdminPendingInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getAdminTasksByCompletion' : IDL.Func(
        [IDL.Bool],
        [IDL.Vec(Task)],
        ['query'],
      ),
    'getAdminTasksByPriority' : IDL.Func(
        [Priority],
        [IDL.Vec(Task)],
        ['query'],
      ),
    'getAdminUnpaidInvoiceReminders' : IDL.Func(
        [],
        [IDL.Vec(InvoiceReminder)],
        ['query'],
      ),
    'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getAllMeetings' : IDL.Func([], [IDL.Vec(Meeting)], ['query']),
    'getAllReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getAllWorkflowRules' : IDL.Func(
        [],
        [IDL.Vec(WorkflowAutomationRule)],
        ['query'],
      ),
    'getAppointment' : IDL.Func([IDL.Text], [Appointment], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatGroups' : IDL.Func([], [IDL.Vec(ChatGroup)], ['query']),
    'getClient' : IDL.Func([IDL.Text], [Client], ['query']),
    'getInvoice' : IDL.Func([IDL.Text], [Invoice], ['query']),
    'getInvoiceReminders' : IDL.Func([], [IDL.Vec(InvoiceReminder)], ['query']),
    'getKanbanBoard' : IDL.Func([], [KanbanBoard], ['query']),
    'getMailNotifications' : IDL.Func(
        [],
        [IDL.Vec(MailNotification)],
        ['query'],
      ),
    'getMeeting' : IDL.Func([IDL.Text], [Meeting], ['query']),
    'getMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getProductivitySummary' : IDL.Func([], [ProductivitySummary], ['query']),
    'getReminder' : IDL.Func([IDL.Text], [Reminder], ['query']),
    'getSchedulingSuggestions' : IDL.Func(
        [],
        [SchedulingSuggestions],
        ['query'],
      ),
    'getTask' : IDL.Func([IDL.Text], [Task], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkflowAutomationLogs' : IDL.Func(
        [],
        [IDL.Vec(WorkflowAutomationLogEntry)],
        ['query'],
      ),
    'getWorkflowRule' : IDL.Func(
        [IDL.Text],
        [WorkflowAutomationRule],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isDatabaseAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logWorkflowAutomation' : IDL.Func([WorkflowAutomationLogEntry], [], []),
    'markMailAsRead' : IDL.Func([IDL.Text], [], []),
    'markNotificationAsRead' : IDL.Func([IDL.Text], [], []),
    'recordInvoicePayment' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Text, Message], [], []),
    'updateAppointment' : IDL.Func([IDL.Text, Appointment], [], []),
    'updateClient' : IDL.Func([IDL.Text, Client], [], []),
    'updateInvoice' : IDL.Func([IDL.Text, Invoice], [], []),
    'updateKanbanBoard' : IDL.Func([KanbanBoard], [], []),
    'updateMeeting' : IDL.Func([IDL.Text, Meeting], [], []),
    'updateReminder' : IDL.Func([IDL.Text, Reminder], [], []),
    'updateTask' : IDL.Func([IDL.Text, Task], [], []),
    'updateWorkflowRule' : IDL.Func([IDL.Text, WorkflowAutomationRule], [], []),
    'validateDatabaseAccess' : IDL.Func([], [], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };