/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : string,
  'status' : AppointmentStatus,
  'serviceType' : string,
  'clientId' : [] | [string],
  'associatedUser' : Principal,
  'clientName' : string,
  'dateTime' : Time,
}
export type AppointmentStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export type AutomationAction = { 'createNotification' : Notification } |
  { 'createTask' : Task } |
  { 'createMeeting' : Meeting } |
  { 'createAppointment' : Appointment } |
  { 'createReminder' : Reminder };
export interface AutomationEvent {
  'id' : string,
  'action' : string,
  'trigger' : AutomationTrigger,
  'timestamp' : Time,
}
export type AutomationStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null } |
  { 'failed' : null };
export type AutomationTrigger = { 'taskCompleted' : string } |
  { 'meetingEnded' : string } |
  { 'clientCreated' : string };
export interface ChatGroup {
  'id' : string,
  'creator' : Principal,
  'members' : Array<Principal>,
}
export interface Client {
  'id' : string,
  'owner' : Principal,
  'name' : string,
  'email' : string,
  'company' : string,
  'notes' : string,
  'phone' : string,
}
export interface EntityCount {
  'automationLogs' : bigint,
  'tasks' : bigint,
  'notifications' : bigint,
  'meetings' : bigint,
  'messages' : bigint,
  'userProfiles' : bigint,
  'appointments' : bigint,
  'invoices' : bigint,
  'invoiceReminders' : bigint,
  'kanbanBoards' : bigint,
  'reminders' : bigint,
  'chatGroups' : bigint,
  'mailNotifications' : bigint,
  'clients' : bigint,
  'workflowRules' : bigint,
}
export interface Invoice {
  'id' : string,
  'status' : InvoiceStatus,
  'clientId' : string,
  'owner' : Principal,
  'dueDate' : Time,
  'workDescription' : string,
  'amount' : bigint,
}
export interface InvoiceReminder {
  'id' : string,
  'userId' : Principal,
  'dueDate' : Time,
  'invoiceId' : string,
  'reminderTime' : Time,
  'message' : string,
}
export type InvoiceStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'overdue' : null };
export interface KanbanBoard {
  'layout' : Array<string>,
  'columns' : Array<KanbanColumn>,
}
export interface KanbanColumn { 'name' : string, 'taskOrder' : Array<string> }
export interface MailNotification {
  'id' : string,
  'subject' : string,
  'source' : string,
  'read' : boolean,
  'user' : Principal,
  'sender' : MailSender,
  'timestamp' : Time,
}
export interface MailSender { 'displayName' : string, 'address' : string }
export interface Meeting {
  'id' : string,
  'startTime' : Time,
  'title' : string,
  'creator' : Principal,
  'participants' : Array<Principal>,
  'clientId' : [] | [string],
  'endTime' : Time,
  'description' : string,
}
export interface Message {
  'id' : string,
  'content' : string,
  'sender' : Principal,
  'timestamp' : Time,
}
export interface Notification {
  'id' : string,
  'notificationType' : NotificationType,
  'read' : boolean,
  'user' : Principal,
  'message' : string,
  'timestamp' : Time,
  'mailNotification' : [] | [MailNotification],
}
export type NotificationType = { 'reminder' : null } |
  { 'mail' : null } |
  { 'message' : null };
export type Priority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface ProductivitySummary {
  'overdueTasks' : bigint,
  'activeMeetings' : bigint,
  'availableSlots' : bigint,
  'upcomingReminders' : bigint,
}
export interface Reminder {
  'id' : string,
  'owner' : Principal,
  'time' : Time,
  'message' : string,
}
export interface SchedulingSuggestions {
  'scheduleResolutions' : string,
  'availableTimeBlocks' : Array<Time>,
  'suggestedMeetings' : Array<Meeting>,
}
export interface Task {
  'id' : string,
  'title' : string,
  'clientId' : [] | [string],
  'owner' : Principal,
  'completed' : boolean,
  'dueDate' : Time,
  'description' : string,
  'priority' : Priority,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'department' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkflowAutomationLogEntry {
  'id' : string,
  'status' : AutomationStatus,
  'ruleId' : string,
  'user' : Principal,
  'event' : AutomationEvent,
  'timestamp' : Time,
}
export interface WorkflowAutomationRule {
  'id' : string,
  'action' : AutomationAction,
  'trigger' : AutomationTrigger,
  'enabled' : boolean,
}
export interface _SERVICE {
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAppointment' : ActorMethod<[Appointment], undefined>,
  'createChatGroup' : ActorMethod<[string, Array<Principal>], undefined>,
  'createClient' : ActorMethod<[Client], undefined>,
  'createInvoice' : ActorMethod<[Invoice], undefined>,
  'createInvoiceReminder' : ActorMethod<[InvoiceReminder], undefined>,
  'createMailNotification' : ActorMethod<[MailNotification], undefined>,
  'createMeeting' : ActorMethod<[Meeting], undefined>,
  'createNotification' : ActorMethod<[Notification], undefined>,
  'createReminder' : ActorMethod<[Reminder], undefined>,
  'createTask' : ActorMethod<[Task], undefined>,
  'createWorkflowRule' : ActorMethod<[WorkflowAutomationRule], undefined>,
  'deleteAppointment' : ActorMethod<[string], undefined>,
  'deleteClient' : ActorMethod<[string], undefined>,
  'deleteInvoice' : ActorMethod<[string], undefined>,
  'deleteInvoiceReminder' : ActorMethod<[string], undefined>,
  'deleteMailNotification' : ActorMethod<[string], undefined>,
  'deleteMeeting' : ActorMethod<[string], undefined>,
  'deleteNotification' : ActorMethod<[string], undefined>,
  'deleteReminder' : ActorMethod<[string], undefined>,
  'deleteTask' : ActorMethod<[string], undefined>,
  'deleteWorkflowRule' : ActorMethod<[string], undefined>,
  'getAdminAllAppointments' : ActorMethod<[], Array<Appointment>>,
  'getAdminAllChatGroups' : ActorMethod<[], Array<ChatGroup>>,
  'getAdminAllClients' : ActorMethod<[], Array<Client>>,
  'getAdminAllInvoiceReminders' : ActorMethod<[], Array<InvoiceReminder>>,
  'getAdminAllInvoices' : ActorMethod<[], Array<Invoice>>,
  'getAdminAllKanbanBoards' : ActorMethod<[], Array<[Principal, KanbanBoard]>>,
  'getAdminAllMailNotifications' : ActorMethod<[], Array<MailNotification>>,
  'getAdminAllMeetings' : ActorMethod<[], Array<Meeting>>,
  'getAdminAllMessages' : ActorMethod<[], Array<[string, Array<Message>]>>,
  'getAdminAllNotifications' : ActorMethod<[], Array<Notification>>,
  'getAdminAllReminders' : ActorMethod<[], Array<Reminder>>,
  'getAdminAllTasks' : ActorMethod<[], Array<Task>>,
  'getAdminAllUserProfiles' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getAdminAllWorkflowLogs' : ActorMethod<
    [],
    Array<WorkflowAutomationLogEntry>
  >,
  'getAdminAllWorkflowRules' : ActorMethod<[], Array<WorkflowAutomationRule>>,
  'getAdminDueReminders' : ActorMethod<[Time], Array<Reminder>>,
  'getAdminEntityCounts' : ActorMethod<[], EntityCount>,
  'getAdminPendingInvoices' : ActorMethod<[], Array<Invoice>>,
  'getAdminTasksByCompletion' : ActorMethod<[boolean], Array<Task>>,
  'getAdminTasksByPriority' : ActorMethod<[Priority], Array<Task>>,
  'getAdminUnpaidInvoiceReminders' : ActorMethod<[], Array<InvoiceReminder>>,
  'getAllAppointments' : ActorMethod<[], Array<Appointment>>,
  'getAllClients' : ActorMethod<[], Array<Client>>,
  'getAllInvoices' : ActorMethod<[], Array<Invoice>>,
  'getAllMeetings' : ActorMethod<[], Array<Meeting>>,
  'getAllReminders' : ActorMethod<[], Array<Reminder>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getAllWorkflowRules' : ActorMethod<[], Array<WorkflowAutomationRule>>,
  'getAppointment' : ActorMethod<[string], Appointment>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatGroups' : ActorMethod<[], Array<ChatGroup>>,
  'getClient' : ActorMethod<[string], Client>,
  'getInvoice' : ActorMethod<[string], Invoice>,
  'getInvoiceReminders' : ActorMethod<[], Array<InvoiceReminder>>,
  'getKanbanBoard' : ActorMethod<[], KanbanBoard>,
  'getMailNotifications' : ActorMethod<[], Array<MailNotification>>,
  'getMeeting' : ActorMethod<[string], Meeting>,
  'getMessages' : ActorMethod<[string], Array<Message>>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getProductivitySummary' : ActorMethod<[], ProductivitySummary>,
  'getReminder' : ActorMethod<[string], Reminder>,
  'getSchedulingSuggestions' : ActorMethod<[], SchedulingSuggestions>,
  'getTask' : ActorMethod<[string], Task>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkflowAutomationLogs' : ActorMethod<
    [],
    Array<WorkflowAutomationLogEntry>
  >,
  'getWorkflowRule' : ActorMethod<[string], WorkflowAutomationRule>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isDatabaseAdmin' : ActorMethod<[], boolean>,
  'logWorkflowAutomation' : ActorMethod<
    [WorkflowAutomationLogEntry],
    undefined
  >,
  'markMailAsRead' : ActorMethod<[string], undefined>,
  'markNotificationAsRead' : ActorMethod<[string], undefined>,
  'recordInvoicePayment' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[string, Message], undefined>,
  'updateAppointment' : ActorMethod<[string, Appointment], undefined>,
  'updateClient' : ActorMethod<[string, Client], undefined>,
  'updateInvoice' : ActorMethod<[string, Invoice], undefined>,
  'updateKanbanBoard' : ActorMethod<[KanbanBoard], undefined>,
  'updateMeeting' : ActorMethod<[string, Meeting], undefined>,
  'updateReminder' : ActorMethod<[string, Reminder], undefined>,
  'updateTask' : ActorMethod<[string, Task], undefined>,
  'updateWorkflowRule' : ActorMethod<
    [string, WorkflowAutomationRule],
    undefined
  >,
  'validateDatabaseAccess' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];