/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface WorkflowAutomationRule {
    id: string;
    action: AutomationAction;
    trigger: AutomationTrigger;
    enabled: boolean;
}
export type Time = bigint;
export interface Meeting {
    id: string;
    startTime: Time;
    title: string;
    creator: Principal;
    participants: Array<Principal>;
    clientId?: string;
    endTime: Time;
    description: string;
}
export interface WorkflowAutomationLogEntry {
    id: string;
    status: AutomationStatus;
    ruleId: string;
    user: Principal;
    event: AutomationEvent;
    timestamp: Time;
}
export interface KanbanColumn {
    name: string;
    taskOrder: Array<string>;
}
export type AutomationAction = {
    __kind__: "createNotification";
    createNotification: Notification;
} | {
    __kind__: "createTask";
    createTask: Task;
} | {
    __kind__: "createMeeting";
    createMeeting: Meeting;
} | {
    __kind__: "createAppointment";
    createAppointment: Appointment;
} | {
    __kind__: "createReminder";
    createReminder: Reminder;
};
export interface Task {
    id: string;
    title: string;
    clientId?: string;
    owner: Principal;
    completed: boolean;
    dueDate: Time;
    description: string;
    priority: Priority;
}
export interface AutomationEvent {
    id: string;
    action: string;
    trigger: AutomationTrigger;
    timestamp: Time;
}
export interface KanbanBoard {
    layout: Array<string>;
    columns: Array<KanbanColumn>;
}
export interface MailNotification {
    id: string;
    subject: string;
    source: string;
    read: boolean;
    user: Principal;
    sender: MailSender;
    timestamp: Time;
}
export interface InvoiceReminder {
    id: string;
    userId: Principal;
    dueDate: Time;
    invoiceId: string;
    reminderTime: Time;
    message: string;
}
export type AutomationTrigger = {
    __kind__: "taskCompleted";
    taskCompleted: string;
} | {
    __kind__: "meetingEnded";
    meetingEnded: string;
} | {
    __kind__: "clientCreated";
    clientCreated: string;
};
export interface Reminder {
    id: string;
    owner: Principal;
    time: Time;
    message: string;
}
export interface MailSender {
    displayName: string;
    address: string;
}
export interface Client {
    id: string;
    owner: Principal;
    name: string;
    email: string;
    company: string;
    notes: string;
    phone: string;
}
export interface ChatGroup {
    id: string;
    creator: Principal;
    members: Array<Principal>;
}
export interface SchedulingSuggestions {
    scheduleResolutions: string;
    availableTimeBlocks: Array<Time>;
    suggestedMeetings: Array<Meeting>;
}
export interface Invoice {
    id: string;
    status: InvoiceStatus;
    clientId: string;
    owner: Principal;
    dueDate: Time;
    workDescription: string;
    amount: bigint;
}
export interface Notification {
    id: string;
    notificationType: NotificationType;
    read: boolean;
    user: Principal;
    message: string;
    timestamp: Time;
    mailNotification?: MailNotification;
}
export interface EntityCount {
    automationLogs: bigint;
    tasks: bigint;
    notifications: bigint;
    meetings: bigint;
    messages: bigint;
    userProfiles: bigint;
    appointments: bigint;
    invoices: bigint;
    invoiceReminders: bigint;
    kanbanBoards: bigint;
    reminders: bigint;
    chatGroups: bigint;
    mailNotifications: bigint;
    clients: bigint;
    workflowRules: bigint;
}
export interface Message {
    id: string;
    content: string;
    sender: Principal;
    timestamp: Time;
}
export interface Appointment {
    id: string;
    status: AppointmentStatus;
    serviceType: string;
    clientId?: string;
    associatedUser: Principal;
    clientName: string;
    dateTime: Time;
}
export interface ProductivitySummary {
    overdueTasks: bigint;
    activeMeetings: bigint;
    availableSlots: bigint;
    upcomingReminders: bigint;
}
export interface UserProfile {
    name: string;
    department: string;
}
export enum AppointmentStatus {
    pending = "pending",
    completed = "completed",
    confirmed = "confirmed"
}
export enum AutomationStatus {
    pending = "pending",
    completed = "completed",
    inProgress = "inProgress",
    failed = "failed"
}
export enum InvoiceStatus {
    pending = "pending",
    paid = "paid",
    overdue = "overdue"
}
export enum NotificationType {
    reminder = "reminder",
    mail = "mail",
    message = "message"
}
export enum Priority {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAppointment(appointment: Appointment): Promise<void>;
    createChatGroup(groupId: string, members: Array<Principal>): Promise<void>;
    createClient(client: Client): Promise<void>;
    createInvoice(invoice: Invoice): Promise<void>;
    createInvoiceReminder(reminder: InvoiceReminder): Promise<void>;
    createMailNotification(mail: MailNotification): Promise<void>;
    createMeeting(meeting: Meeting): Promise<void>;
    createNotification(notification: Notification): Promise<void>;
    createReminder(reminder: Reminder): Promise<void>;
    createTask(task: Task): Promise<void>;
    createWorkflowRule(rule: WorkflowAutomationRule): Promise<void>;
    deleteAppointment(appointmentId: string): Promise<void>;
    deleteClient(clientId: string): Promise<void>;
    deleteInvoice(invoiceId: string): Promise<void>;
    deleteInvoiceReminder(reminderId: string): Promise<void>;
    deleteMailNotification(mailId: string): Promise<void>;
    deleteMeeting(meetingId: string): Promise<void>;
    deleteNotification(notificationId: string): Promise<void>;
    deleteReminder(reminderId: string): Promise<void>;
    deleteTask(taskId: string): Promise<void>;
    deleteWorkflowRule(ruleId: string): Promise<void>;
    getAdminAllAppointments(): Promise<Array<Appointment>>;
    getAdminAllChatGroups(): Promise<Array<ChatGroup>>;
    getAdminAllClients(): Promise<Array<Client>>;
    getAdminAllInvoiceReminders(): Promise<Array<InvoiceReminder>>;
    getAdminAllInvoices(): Promise<Array<Invoice>>;
    getAdminAllKanbanBoards(): Promise<Array<[Principal, KanbanBoard]>>;
    getAdminAllMailNotifications(): Promise<Array<MailNotification>>;
    getAdminAllMeetings(): Promise<Array<Meeting>>;
    getAdminAllMessages(): Promise<Array<[string, Array<Message>]>>;
    getAdminAllNotifications(): Promise<Array<Notification>>;
    getAdminAllReminders(): Promise<Array<Reminder>>;
    getAdminAllTasks(): Promise<Array<Task>>;
    getAdminAllUserProfiles(): Promise<Array<[Principal, UserProfile]>>;
    getAdminAllWorkflowLogs(): Promise<Array<WorkflowAutomationLogEntry>>;
    getAdminAllWorkflowRules(): Promise<Array<WorkflowAutomationRule>>;
    getAdminDueReminders(maxTime: Time): Promise<Array<Reminder>>;
    getAdminEntityCounts(): Promise<EntityCount>;
    getAdminPendingInvoices(): Promise<Array<Invoice>>;
    getAdminTasksByCompletion(completed: boolean): Promise<Array<Task>>;
    getAdminTasksByPriority(priority: Priority): Promise<Array<Task>>;
    getAdminUnpaidInvoiceReminders(): Promise<Array<InvoiceReminder>>;
    getAllAppointments(): Promise<Array<Appointment>>;
    getAllClients(): Promise<Array<Client>>;
    getAllInvoices(): Promise<Array<Invoice>>;
    getAllMeetings(): Promise<Array<Meeting>>;
    getAllReminders(): Promise<Array<Reminder>>;
    getAllTasks(): Promise<Array<Task>>;
    getAllWorkflowRules(): Promise<Array<WorkflowAutomationRule>>;
    getAppointment(appointmentId: string): Promise<Appointment>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChatGroups(): Promise<Array<ChatGroup>>;
    getClient(clientId: string): Promise<Client>;
    getInvoice(invoiceId: string): Promise<Invoice>;
    getInvoiceReminders(): Promise<Array<InvoiceReminder>>;
    getKanbanBoard(): Promise<KanbanBoard>;
    getMailNotifications(): Promise<Array<MailNotification>>;
    getMeeting(meetingId: string): Promise<Meeting>;
    getMessages(groupId: string): Promise<Array<Message>>;
    getNotifications(): Promise<Array<Notification>>;
    getProductivitySummary(): Promise<ProductivitySummary>;
    getReminder(reminderId: string): Promise<Reminder>;
    getSchedulingSuggestions(): Promise<SchedulingSuggestions>;
    getTask(taskId: string): Promise<Task>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWorkflowAutomationLogs(): Promise<Array<WorkflowAutomationLogEntry>>;
    getWorkflowRule(ruleId: string): Promise<WorkflowAutomationRule>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isDatabaseAdmin(): Promise<boolean>;
    logWorkflowAutomation(logEntry: WorkflowAutomationLogEntry): Promise<void>;
    markMailAsRead(mailId: string): Promise<void>;
    markNotificationAsRead(notificationId: string): Promise<void>;
    recordInvoicePayment(id: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendMessage(groupId: string, message: Message): Promise<void>;
    updateAppointment(appointmentId: string, updatedAppointment: Appointment): Promise<void>;
    updateClient(clientId: string, updatedClient: Client): Promise<void>;
    updateInvoice(invoiceId: string, updatedInvoice: Invoice): Promise<void>;
    updateKanbanBoard(board: KanbanBoard): Promise<void>;
    updateMeeting(meetingId: string, updatedMeeting: Meeting): Promise<void>;
    updateReminder(reminderId: string, updatedReminder: Reminder): Promise<void>;
    updateTask(taskId: string, updatedTask: Task): Promise<void>;
    updateWorkflowRule(ruleId: string, updatedRule: WorkflowAutomationRule): Promise<void>;
    validateDatabaseAccess(): Promise<void>;
}
import type { Appointment as _Appointment, AppointmentStatus as _AppointmentStatus, AutomationAction as _AutomationAction, AutomationEvent as _AutomationEvent, AutomationStatus as _AutomationStatus, AutomationTrigger as _AutomationTrigger, Invoice as _Invoice, InvoiceStatus as _InvoiceStatus, MailNotification as _MailNotification, Meeting as _Meeting, Notification as _Notification, NotificationType as _NotificationType, Priority as _Priority, Reminder as _Reminder, SchedulingSuggestions as _SchedulingSuggestions, Task as _Task, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, WorkflowAutomationLogEntry as _WorkflowAutomationLogEntry, WorkflowAutomationRule as _WorkflowAutomationRule } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async createAppointment(arg0: Appointment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createAppointment(to_candid_Appointment_n3(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAppointment(to_candid_Appointment_n3(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async createChatGroup(arg0: string, arg1: Array<Principal>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createChatGroup(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createChatGroup(arg0, arg1);
            return result;
        }
    }
    async createClient(arg0: Client): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClient(arg0);
            return result;
        }
    }
    async createInvoice(arg0: Invoice): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvoice(to_candid_Invoice_n7(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvoice(to_candid_Invoice_n7(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async createInvoiceReminder(arg0: InvoiceReminder): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvoiceReminder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvoiceReminder(arg0);
            return result;
        }
    }
    async createMailNotification(arg0: MailNotification): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createMailNotification(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMailNotification(arg0);
            return result;
        }
    }
    async createMeeting(arg0: Meeting): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createMeeting(to_candid_Meeting_n11(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMeeting(to_candid_Meeting_n11(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async createNotification(arg0: Notification): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createNotification(to_candid_Notification_n13(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNotification(to_candid_Notification_n13(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async createReminder(arg0: Reminder): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createReminder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReminder(arg0);
            return result;
        }
    }
    async createTask(arg0: Task): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(to_candid_Task_n17(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(to_candid_Task_n17(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async createWorkflowRule(arg0: WorkflowAutomationRule): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createWorkflowRule(to_candid_WorkflowAutomationRule_n21(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWorkflowRule(to_candid_WorkflowAutomationRule_n21(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async deleteAppointment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAppointment(arg0);
            return result;
        }
    }
    async deleteClient(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClient(arg0);
            return result;
        }
    }
    async deleteInvoice(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInvoice(arg0);
            return result;
        }
    }
    async deleteInvoiceReminder(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInvoiceReminder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInvoiceReminder(arg0);
            return result;
        }
    }
    async deleteMailNotification(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMailNotification(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMailNotification(arg0);
            return result;
        }
    }
    async deleteMeeting(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMeeting(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMeeting(arg0);
            return result;
        }
    }
    async deleteNotification(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNotification(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNotification(arg0);
            return result;
        }
    }
    async deleteReminder(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReminder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReminder(arg0);
            return result;
        }
    }
    async deleteTask(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async deleteWorkflowRule(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWorkflowRule(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWorkflowRule(arg0);
            return result;
        }
    }
    async getAdminAllAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminAllAppointments();
                return from_candid_vec_n27(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminAllAppointments();
            return from_candid_vec_n27(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAdminAllChatGroups(): Promise<Array<ChatGroup>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminAllChatGroups();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminAllChatGroups();
            return result;
        }
    }
    async getAdminAllClients(): Promise<Array<Client>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminAllClients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminAllClients();
            return result;
        }
    }
    async getAdminAllInvoiceReminders(): Promise<Array<InvoiceReminder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminAllInvoiceReminders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminAllInvoiceReminders();
            return result;
        }
    }
    async getAdminAllInvoices(): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminAllInvoices();
                return from_candid_vec_n33(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminAllInvoices();
            return from_candid_vec_n33(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAdminAllKanbanBoards(): Promise<Array<[Principal, KanbanBoard]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminAllKanbanBoards();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminAllKanbanBoards();
            return result;
        }
    }
    async getAdminAllMailNotifications(): Promise<Array<MailNotification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminAllMailNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminAllMailNotifications();
            return result;
        }
    }
    async getAdminAllMeetings(): Promise<Array<Meeting>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminAllMeetings();
                return from_candid_vec_n38(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminAllMeetings();
            return from_candid_vec_n38(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAdminAllMessages(): Promise<Array<[string, Array<Message>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminAllMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminAllMessages();
            return result;
        }
    }
    async getAdminAllNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminAllNotifications();
                return from_candid_vec_n41(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminAllNotifications();
            return from_candid_vec_n41(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAdminAllReminders(): Promise<Array<Reminder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminAllReminders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminAllReminders();
            return result;
        }
    }
    async getAdminAllTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminAllTasks();
                return from_candid_vec_n47(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminAllTasks();
            return from_candid_vec_n47(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAdminAllUserProfiles(): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminAllUserProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminAllUserProfiles();
            return result;
        }
    }
    async getAdminAllWorkflowLogs(): Promise<Array<WorkflowAutomationLogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminAllWorkflowLogs();
                return from_candid_vec_n52(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminAllWorkflowLogs();
            return from_candid_vec_n52(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAdminAllWorkflowRules(): Promise<Array<WorkflowAutomationRule>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminAllWorkflowRules();
                return from_candid_vec_n61(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminAllWorkflowRules();
            return from_candid_vec_n61(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAdminDueReminders(arg0: Time): Promise<Array<Reminder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminDueReminders(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminDueReminders(arg0);
            return result;
        }
    }
    async getAdminEntityCounts(): Promise<EntityCount> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminEntityCounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminEntityCounts();
            return result;
        }
    }
    async getAdminPendingInvoices(): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminPendingInvoices();
                return from_candid_vec_n33(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminPendingInvoices();
            return from_candid_vec_n33(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAdminTasksByCompletion(arg0: boolean): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminTasksByCompletion(arg0);
                return from_candid_vec_n47(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminTasksByCompletion(arg0);
            return from_candid_vec_n47(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAdminTasksByPriority(arg0: Priority): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminTasksByPriority(to_candid_Priority_n19(this.uploadFile, this.downloadFile, arg0));
                return from_candid_vec_n47(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminTasksByPriority(to_candid_Priority_n19(this.uploadFile, this.downloadFile, arg0));
            return from_candid_vec_n47(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAdminUnpaidInvoiceReminders(): Promise<Array<InvoiceReminder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminUnpaidInvoiceReminders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminUnpaidInvoiceReminders();
            return result;
        }
    }
    async getAllAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAppointments();
                return from_candid_vec_n27(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAppointments();
            return from_candid_vec_n27(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllClients(): Promise<Array<Client>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClients();
            return result;
        }
    }
    async getAllInvoices(): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInvoices();
                return from_candid_vec_n33(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInvoices();
            return from_candid_vec_n33(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllMeetings(): Promise<Array<Meeting>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMeetings();
                return from_candid_vec_n38(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMeetings();
            return from_candid_vec_n38(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllReminders(): Promise<Array<Reminder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReminders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReminders();
            return result;
        }
    }
    async getAllTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTasks();
                return from_candid_vec_n47(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTasks();
            return from_candid_vec_n47(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllWorkflowRules(): Promise<Array<WorkflowAutomationRule>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWorkflowRules();
                return from_candid_vec_n61(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWorkflowRules();
            return from_candid_vec_n61(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAppointment(arg0: string): Promise<Appointment> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointment(arg0);
                return from_candid_Appointment_n28(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointment(arg0);
            return from_candid_Appointment_n28(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n66(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n66(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n67(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n67(this.uploadFile, this.downloadFile, result);
        }
    }
    async getChatGroups(): Promise<Array<ChatGroup>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatGroups();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatGroups();
            return result;
        }
    }
    async getClient(arg0: string): Promise<Client> {
        if (this.processError) {
            try {
                const result = await this.actor.getClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClient(arg0);
            return result;
        }
    }
    async getInvoice(arg0: string): Promise<Invoice> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoice(arg0);
                return from_candid_Invoice_n34(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoice(arg0);
            return from_candid_Invoice_n34(this.uploadFile, this.downloadFile, result);
        }
    }
    async getInvoiceReminders(): Promise<Array<InvoiceReminder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoiceReminders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoiceReminders();
            return result;
        }
    }
    async getKanbanBoard(): Promise<KanbanBoard> {
        if (this.processError) {
            try {
                const result = await this.actor.getKanbanBoard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKanbanBoard();
            return result;
        }
    }
    async getMailNotifications(): Promise<Array<MailNotification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMailNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMailNotifications();
            return result;
        }
    }
    async getMeeting(arg0: string): Promise<Meeting> {
        if (this.processError) {
            try {
                const result = await this.actor.getMeeting(arg0);
                return from_candid_Meeting_n39(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMeeting(arg0);
            return from_candid_Meeting_n39(this.uploadFile, this.downloadFile, result);
        }
    }
    async getMessages(arg0: string): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0);
            return result;
        }
    }
    async getNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications();
                return from_candid_vec_n41(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications();
            return from_candid_vec_n41(this.uploadFile, this.downloadFile, result);
        }
    }
    async getProductivitySummary(): Promise<ProductivitySummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductivitySummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductivitySummary();
            return result;
        }
    }
    async getReminder(arg0: string): Promise<Reminder> {
        if (this.processError) {
            try {
                const result = await this.actor.getReminder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReminder(arg0);
            return result;
        }
    }
    async getSchedulingSuggestions(): Promise<SchedulingSuggestions> {
        if (this.processError) {
            try {
                const result = await this.actor.getSchedulingSuggestions();
                return from_candid_SchedulingSuggestions_n69(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSchedulingSuggestions();
            return from_candid_SchedulingSuggestions_n69(this.uploadFile, this.downloadFile, result);
        }
    }
    async getTask(arg0: string): Promise<Task> {
        if (this.processError) {
            try {
                const result = await this.actor.getTask(arg0);
                return from_candid_Task_n48(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTask(arg0);
            return from_candid_Task_n48(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n66(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n66(this.uploadFile, this.downloadFile, result);
        }
    }
    async getWorkflowAutomationLogs(): Promise<Array<WorkflowAutomationLogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkflowAutomationLogs();
                return from_candid_vec_n52(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkflowAutomationLogs();
            return from_candid_vec_n52(this.uploadFile, this.downloadFile, result);
        }
    }
    async getWorkflowRule(arg0: string): Promise<WorkflowAutomationRule> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkflowRule(arg0);
                return from_candid_WorkflowAutomationRule_n62(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkflowRule(arg0);
            return from_candid_WorkflowAutomationRule_n62(this.uploadFile, this.downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isDatabaseAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isDatabaseAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isDatabaseAdmin();
            return result;
        }
    }
    async logWorkflowAutomation(arg0: WorkflowAutomationLogEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logWorkflowAutomation(to_candid_WorkflowAutomationLogEntry_n71(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logWorkflowAutomation(to_candid_WorkflowAutomationLogEntry_n71(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async markMailAsRead(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markMailAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markMailAsRead(arg0);
            return result;
        }
    }
    async markNotificationAsRead(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationAsRead(arg0);
            return result;
        }
    }
    async recordInvoicePayment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordInvoicePayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordInvoicePayment(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async sendMessage(arg0: string, arg1: Message): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async updateAppointment(arg0: string, arg1: Appointment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAppointment(arg0, to_candid_Appointment_n3(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAppointment(arg0, to_candid_Appointment_n3(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async updateClient(arg0: string, arg1: Client): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClient(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClient(arg0, arg1);
            return result;
        }
    }
    async updateInvoice(arg0: string, arg1: Invoice): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInvoice(arg0, to_candid_Invoice_n7(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInvoice(arg0, to_candid_Invoice_n7(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async updateKanbanBoard(arg0: KanbanBoard): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateKanbanBoard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateKanbanBoard(arg0);
            return result;
        }
    }
    async updateMeeting(arg0: string, arg1: Meeting): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMeeting(arg0, to_candid_Meeting_n11(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMeeting(arg0, to_candid_Meeting_n11(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async updateReminder(arg0: string, arg1: Reminder): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReminder(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReminder(arg0, arg1);
            return result;
        }
    }
    async updateTask(arg0: string, arg1: Task): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0, to_candid_Task_n17(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0, to_candid_Task_n17(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async updateWorkflowRule(arg0: string, arg1: WorkflowAutomationRule): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWorkflowRule(arg0, to_candid_WorkflowAutomationRule_n21(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWorkflowRule(arg0, to_candid_WorkflowAutomationRule_n21(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async validateDatabaseAccess(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.validateDatabaseAccess();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateDatabaseAccess();
            return result;
        }
    }
}
function from_candid_AppointmentStatus_n30(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppointmentStatus): AppointmentStatus {
    return from_candid_variant_n31(uploadFile, downloadFile, value);
}
function from_candid_Appointment_n28(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Appointment): Appointment {
    return from_candid_record_n29(uploadFile, downloadFile, value);
}
function from_candid_AutomationAction_n64(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AutomationAction): AutomationAction {
    return from_candid_variant_n65(uploadFile, downloadFile, value);
}
function from_candid_AutomationEvent_n57(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AutomationEvent): AutomationEvent {
    return from_candid_record_n58(uploadFile, downloadFile, value);
}
function from_candid_AutomationStatus_n55(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AutomationStatus): AutomationStatus {
    return from_candid_variant_n56(uploadFile, downloadFile, value);
}
function from_candid_AutomationTrigger_n59(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AutomationTrigger): AutomationTrigger {
    return from_candid_variant_n60(uploadFile, downloadFile, value);
}
function from_candid_InvoiceStatus_n36(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvoiceStatus): InvoiceStatus {
    return from_candid_variant_n37(uploadFile, downloadFile, value);
}
function from_candid_Invoice_n34(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Invoice): Invoice {
    return from_candid_record_n35(uploadFile, downloadFile, value);
}
function from_candid_Meeting_n39(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Meeting): Meeting {
    return from_candid_record_n40(uploadFile, downloadFile, value);
}
function from_candid_NotificationType_n44(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n45(uploadFile, downloadFile, value);
}
function from_candid_Notification_n42(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n43(uploadFile, downloadFile, value);
}
function from_candid_Priority_n50(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Priority): Priority {
    return from_candid_variant_n51(uploadFile, downloadFile, value);
}
function from_candid_SchedulingSuggestions_n69(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SchedulingSuggestions): SchedulingSuggestions {
    return from_candid_record_n70(uploadFile, downloadFile, value);
}
function from_candid_Task_n48(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n49(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n67(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n68(uploadFile, downloadFile, value);
}
function from_candid_WorkflowAutomationLogEntry_n53(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkflowAutomationLogEntry): WorkflowAutomationLogEntry {
    return from_candid_record_n54(uploadFile, downloadFile, value);
}
function from_candid_WorkflowAutomationRule_n62(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkflowAutomationRule): WorkflowAutomationRule {
    return from_candid_record_n63(uploadFile, downloadFile, value);
}
function from_candid_opt_n32(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n46(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MailNotification]): MailNotification | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n66(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n29(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _AppointmentStatus;
    serviceType: string;
    clientId: [] | [string];
    associatedUser: Principal;
    clientName: string;
    dateTime: _Time;
}): {
    id: string;
    status: AppointmentStatus;
    serviceType: string;
    clientId?: string;
    associatedUser: Principal;
    clientName: string;
    dateTime: Time;
} {
    return {
        id: value.id,
        status: from_candid_AppointmentStatus_n30(uploadFile, downloadFile, value.status),
        serviceType: value.serviceType,
        clientId: record_opt_to_undefined(from_candid_opt_n32(uploadFile, downloadFile, value.clientId)),
        associatedUser: value.associatedUser,
        clientName: value.clientName,
        dateTime: value.dateTime
    };
}
function from_candid_record_n35(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _InvoiceStatus;
    clientId: string;
    owner: Principal;
    dueDate: _Time;
    workDescription: string;
    amount: bigint;
}): {
    id: string;
    status: InvoiceStatus;
    clientId: string;
    owner: Principal;
    dueDate: Time;
    workDescription: string;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_InvoiceStatus_n36(uploadFile, downloadFile, value.status),
        clientId: value.clientId,
        owner: value.owner,
        dueDate: value.dueDate,
        workDescription: value.workDescription,
        amount: value.amount
    };
}
function from_candid_record_n40(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    startTime: _Time;
    title: string;
    creator: Principal;
    participants: Array<Principal>;
    clientId: [] | [string];
    endTime: _Time;
    description: string;
}): {
    id: string;
    startTime: Time;
    title: string;
    creator: Principal;
    participants: Array<Principal>;
    clientId?: string;
    endTime: Time;
    description: string;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        title: value.title,
        creator: value.creator,
        participants: value.participants,
        clientId: record_opt_to_undefined(from_candid_opt_n32(uploadFile, downloadFile, value.clientId)),
        endTime: value.endTime,
        description: value.description
    };
}
function from_candid_record_n43(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    notificationType: _NotificationType;
    read: boolean;
    user: Principal;
    message: string;
    timestamp: _Time;
    mailNotification: [] | [_MailNotification];
}): {
    id: string;
    notificationType: NotificationType;
    read: boolean;
    user: Principal;
    message: string;
    timestamp: Time;
    mailNotification?: MailNotification;
} {
    return {
        id: value.id,
        notificationType: from_candid_NotificationType_n44(uploadFile, downloadFile, value.notificationType),
        read: value.read,
        user: value.user,
        message: value.message,
        timestamp: value.timestamp,
        mailNotification: record_opt_to_undefined(from_candid_opt_n46(uploadFile, downloadFile, value.mailNotification))
    };
}
function from_candid_record_n49(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    clientId: [] | [string];
    owner: Principal;
    completed: boolean;
    dueDate: _Time;
    description: string;
    priority: _Priority;
}): {
    id: string;
    title: string;
    clientId?: string;
    owner: Principal;
    completed: boolean;
    dueDate: Time;
    description: string;
    priority: Priority;
} {
    return {
        id: value.id,
        title: value.title,
        clientId: record_opt_to_undefined(from_candid_opt_n32(uploadFile, downloadFile, value.clientId)),
        owner: value.owner,
        completed: value.completed,
        dueDate: value.dueDate,
        description: value.description,
        priority: from_candid_Priority_n50(uploadFile, downloadFile, value.priority)
    };
}
function from_candid_record_n54(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _AutomationStatus;
    ruleId: string;
    user: Principal;
    event: _AutomationEvent;
    timestamp: _Time;
}): {
    id: string;
    status: AutomationStatus;
    ruleId: string;
    user: Principal;
    event: AutomationEvent;
    timestamp: Time;
} {
    return {
        id: value.id,
        status: from_candid_AutomationStatus_n55(uploadFile, downloadFile, value.status),
        ruleId: value.ruleId,
        user: value.user,
        event: from_candid_AutomationEvent_n57(uploadFile, downloadFile, value.event),
        timestamp: value.timestamp
    };
}
function from_candid_record_n58(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    action: string;
    trigger: _AutomationTrigger;
    timestamp: _Time;
}): {
    id: string;
    action: string;
    trigger: AutomationTrigger;
    timestamp: Time;
} {
    return {
        id: value.id,
        action: value.action,
        trigger: from_candid_AutomationTrigger_n59(uploadFile, downloadFile, value.trigger),
        timestamp: value.timestamp
    };
}
function from_candid_record_n63(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    action: _AutomationAction;
    trigger: _AutomationTrigger;
    enabled: boolean;
}): {
    id: string;
    action: AutomationAction;
    trigger: AutomationTrigger;
    enabled: boolean;
} {
    return {
        id: value.id,
        action: from_candid_AutomationAction_n64(uploadFile, downloadFile, value.action),
        trigger: from_candid_AutomationTrigger_n59(uploadFile, downloadFile, value.trigger),
        enabled: value.enabled
    };
}
function from_candid_record_n70(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduleResolutions: string;
    availableTimeBlocks: Array<_Time>;
    suggestedMeetings: Array<_Meeting>;
}): {
    scheduleResolutions: string;
    availableTimeBlocks: Array<Time>;
    suggestedMeetings: Array<Meeting>;
} {
    return {
        scheduleResolutions: value.scheduleResolutions,
        availableTimeBlocks: value.availableTimeBlocks,
        suggestedMeetings: from_candid_vec_n38(uploadFile, downloadFile, value.suggestedMeetings)
    };
}
function from_candid_variant_n31(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
}): AppointmentStatus {
    return "pending" in value ? AppointmentStatus.pending : "completed" in value ? AppointmentStatus.completed : "confirmed" in value ? AppointmentStatus.confirmed : value;
}
function from_candid_variant_n37(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
} | {
    overdue: null;
}): InvoiceStatus {
    return "pending" in value ? InvoiceStatus.pending : "paid" in value ? InvoiceStatus.paid : "overdue" in value ? InvoiceStatus.overdue : value;
}
function from_candid_variant_n45(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    reminder: null;
} | {
    mail: null;
} | {
    message: null;
}): NotificationType {
    return "reminder" in value ? NotificationType.reminder : "mail" in value ? NotificationType.mail : "message" in value ? NotificationType.message : value;
}
function from_candid_variant_n51(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): Priority {
    return "low" in value ? Priority.low : "high" in value ? Priority.high : "medium" in value ? Priority.medium : value;
}
function from_candid_variant_n56(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
} | {
    failed: null;
}): AutomationStatus {
    return "pending" in value ? AutomationStatus.pending : "completed" in value ? AutomationStatus.completed : "inProgress" in value ? AutomationStatus.inProgress : "failed" in value ? AutomationStatus.failed : value;
}
function from_candid_variant_n60(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    taskCompleted: string;
} | {
    meetingEnded: string;
} | {
    clientCreated: string;
}): {
    __kind__: "taskCompleted";
    taskCompleted: string;
} | {
    __kind__: "meetingEnded";
    meetingEnded: string;
} | {
    __kind__: "clientCreated";
    clientCreated: string;
} {
    return "taskCompleted" in value ? {
        __kind__: "taskCompleted",
        taskCompleted: value.taskCompleted
    } : "meetingEnded" in value ? {
        __kind__: "meetingEnded",
        meetingEnded: value.meetingEnded
    } : "clientCreated" in value ? {
        __kind__: "clientCreated",
        clientCreated: value.clientCreated
    } : value;
}
function from_candid_variant_n65(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    createNotification: _Notification;
} | {
    createTask: _Task;
} | {
    createMeeting: _Meeting;
} | {
    createAppointment: _Appointment;
} | {
    createReminder: _Reminder;
}): {
    __kind__: "createNotification";
    createNotification: Notification;
} | {
    __kind__: "createTask";
    createTask: Task;
} | {
    __kind__: "createMeeting";
    createMeeting: Meeting;
} | {
    __kind__: "createAppointment";
    createAppointment: Appointment;
} | {
    __kind__: "createReminder";
    createReminder: Reminder;
} {
    return "createNotification" in value ? {
        __kind__: "createNotification",
        createNotification: from_candid_Notification_n42(uploadFile, downloadFile, value.createNotification)
    } : "createTask" in value ? {
        __kind__: "createTask",
        createTask: from_candid_Task_n48(uploadFile, downloadFile, value.createTask)
    } : "createMeeting" in value ? {
        __kind__: "createMeeting",
        createMeeting: from_candid_Meeting_n39(uploadFile, downloadFile, value.createMeeting)
    } : "createAppointment" in value ? {
        __kind__: "createAppointment",
        createAppointment: from_candid_Appointment_n28(uploadFile, downloadFile, value.createAppointment)
    } : "createReminder" in value ? {
        __kind__: "createReminder",
        createReminder: value.createReminder
    } : value;
}
function from_candid_variant_n68(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Appointment>): Array<Appointment> {
    return value.map((x)=>from_candid_Appointment_n28(uploadFile, downloadFile, x));
}
function from_candid_vec_n33(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Invoice>): Array<Invoice> {
    return value.map((x)=>from_candid_Invoice_n34(uploadFile, downloadFile, x));
}
function from_candid_vec_n38(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Meeting>): Array<Meeting> {
    return value.map((x)=>from_candid_Meeting_n39(uploadFile, downloadFile, x));
}
function from_candid_vec_n41(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n42(uploadFile, downloadFile, x));
}
function from_candid_vec_n47(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n48(uploadFile, downloadFile, x));
}
function from_candid_vec_n52(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkflowAutomationLogEntry>): Array<WorkflowAutomationLogEntry> {
    return value.map((x)=>from_candid_WorkflowAutomationLogEntry_n53(uploadFile, downloadFile, x));
}
function from_candid_vec_n61(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkflowAutomationRule>): Array<WorkflowAutomationRule> {
    return value.map((x)=>from_candid_WorkflowAutomationRule_n62(uploadFile, downloadFile, x));
}
function to_candid_AppointmentStatus_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppointmentStatus): _AppointmentStatus {
    return to_candid_variant_n6(uploadFile, downloadFile, value);
}
function to_candid_Appointment_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Appointment): _Appointment {
    return to_candid_record_n4(uploadFile, downloadFile, value);
}
function to_candid_AutomationAction_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AutomationAction): _AutomationAction {
    return to_candid_variant_n24(uploadFile, downloadFile, value);
}
function to_candid_AutomationEvent_n75(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AutomationEvent): _AutomationEvent {
    return to_candid_record_n76(uploadFile, downloadFile, value);
}
function to_candid_AutomationStatus_n73(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AutomationStatus): _AutomationStatus {
    return to_candid_variant_n74(uploadFile, downloadFile, value);
}
function to_candid_AutomationTrigger_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AutomationTrigger): _AutomationTrigger {
    return to_candid_variant_n26(uploadFile, downloadFile, value);
}
function to_candid_InvoiceStatus_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceStatus): _InvoiceStatus {
    return to_candid_variant_n10(uploadFile, downloadFile, value);
}
function to_candid_Invoice_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Invoice): _Invoice {
    return to_candid_record_n8(uploadFile, downloadFile, value);
}
function to_candid_Meeting_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Meeting): _Meeting {
    return to_candid_record_n12(uploadFile, downloadFile, value);
}
function to_candid_NotificationType_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationType): _NotificationType {
    return to_candid_variant_n16(uploadFile, downloadFile, value);
}
function to_candid_Notification_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Notification): _Notification {
    return to_candid_record_n14(uploadFile, downloadFile, value);
}
function to_candid_Priority_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): _Priority {
    return to_candid_variant_n20(uploadFile, downloadFile, value);
}
function to_candid_Task_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Task): _Task {
    return to_candid_record_n18(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(uploadFile, downloadFile, value);
}
function to_candid_WorkflowAutomationLogEntry_n71(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkflowAutomationLogEntry): _WorkflowAutomationLogEntry {
    return to_candid_record_n72(uploadFile, downloadFile, value);
}
function to_candid_WorkflowAutomationRule_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkflowAutomationRule): _WorkflowAutomationRule {
    return to_candid_record_n22(uploadFile, downloadFile, value);
}
function to_candid_record_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    startTime: Time;
    title: string;
    creator: Principal;
    participants: Array<Principal>;
    clientId?: string;
    endTime: Time;
    description: string;
}): {
    id: string;
    startTime: _Time;
    title: string;
    creator: Principal;
    participants: Array<Principal>;
    clientId: [] | [string];
    endTime: _Time;
    description: string;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        title: value.title,
        creator: value.creator,
        participants: value.participants,
        clientId: value.clientId ? candid_some(value.clientId) : candid_none(),
        endTime: value.endTime,
        description: value.description
    };
}
function to_candid_record_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    notificationType: NotificationType;
    read: boolean;
    user: Principal;
    message: string;
    timestamp: Time;
    mailNotification?: MailNotification;
}): {
    id: string;
    notificationType: _NotificationType;
    read: boolean;
    user: Principal;
    message: string;
    timestamp: _Time;
    mailNotification: [] | [_MailNotification];
} {
    return {
        id: value.id,
        notificationType: to_candid_NotificationType_n15(uploadFile, downloadFile, value.notificationType),
        read: value.read,
        user: value.user,
        message: value.message,
        timestamp: value.timestamp,
        mailNotification: value.mailNotification ? candid_some(value.mailNotification) : candid_none()
    };
}
function to_candid_record_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    clientId?: string;
    owner: Principal;
    completed: boolean;
    dueDate: Time;
    description: string;
    priority: Priority;
}): {
    id: string;
    title: string;
    clientId: [] | [string];
    owner: Principal;
    completed: boolean;
    dueDate: _Time;
    description: string;
    priority: _Priority;
} {
    return {
        id: value.id,
        title: value.title,
        clientId: value.clientId ? candid_some(value.clientId) : candid_none(),
        owner: value.owner,
        completed: value.completed,
        dueDate: value.dueDate,
        description: value.description,
        priority: to_candid_Priority_n19(uploadFile, downloadFile, value.priority)
    };
}
function to_candid_record_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    action: AutomationAction;
    trigger: AutomationTrigger;
    enabled: boolean;
}): {
    id: string;
    action: _AutomationAction;
    trigger: _AutomationTrigger;
    enabled: boolean;
} {
    return {
        id: value.id,
        action: to_candid_AutomationAction_n23(uploadFile, downloadFile, value.action),
        trigger: to_candid_AutomationTrigger_n25(uploadFile, downloadFile, value.trigger),
        enabled: value.enabled
    };
}
function to_candid_record_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: AppointmentStatus;
    serviceType: string;
    clientId?: string;
    associatedUser: Principal;
    clientName: string;
    dateTime: Time;
}): {
    id: string;
    status: _AppointmentStatus;
    serviceType: string;
    clientId: [] | [string];
    associatedUser: Principal;
    clientName: string;
    dateTime: _Time;
} {
    return {
        id: value.id,
        status: to_candid_AppointmentStatus_n5(uploadFile, downloadFile, value.status),
        serviceType: value.serviceType,
        clientId: value.clientId ? candid_some(value.clientId) : candid_none(),
        associatedUser: value.associatedUser,
        clientName: value.clientName,
        dateTime: value.dateTime
    };
}
function to_candid_record_n72(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: AutomationStatus;
    ruleId: string;
    user: Principal;
    event: AutomationEvent;
    timestamp: Time;
}): {
    id: string;
    status: _AutomationStatus;
    ruleId: string;
    user: Principal;
    event: _AutomationEvent;
    timestamp: _Time;
} {
    return {
        id: value.id,
        status: to_candid_AutomationStatus_n73(uploadFile, downloadFile, value.status),
        ruleId: value.ruleId,
        user: value.user,
        event: to_candid_AutomationEvent_n75(uploadFile, downloadFile, value.event),
        timestamp: value.timestamp
    };
}
function to_candid_record_n76(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    action: string;
    trigger: AutomationTrigger;
    timestamp: Time;
}): {
    id: string;
    action: string;
    trigger: _AutomationTrigger;
    timestamp: _Time;
} {
    return {
        id: value.id,
        action: value.action,
        trigger: to_candid_AutomationTrigger_n25(uploadFile, downloadFile, value.trigger),
        timestamp: value.timestamp
    };
}
function to_candid_record_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: InvoiceStatus;
    clientId: string;
    owner: Principal;
    dueDate: Time;
    workDescription: string;
    amount: bigint;
}): {
    id: string;
    status: _InvoiceStatus;
    clientId: string;
    owner: Principal;
    dueDate: _Time;
    workDescription: string;
    amount: bigint;
} {
    return {
        id: value.id,
        status: to_candid_InvoiceStatus_n9(uploadFile, downloadFile, value.status),
        clientId: value.clientId,
        owner: value.owner,
        dueDate: value.dueDate,
        workDescription: value.workDescription,
        amount: value.amount
    };
}
function to_candid_variant_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceStatus): {
    pending: null;
} | {
    paid: null;
} | {
    overdue: null;
} {
    return value == InvoiceStatus.pending ? {
        pending: null
    } : value == InvoiceStatus.paid ? {
        paid: null
    } : value == InvoiceStatus.overdue ? {
        overdue: null
    } : value;
}
function to_candid_variant_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationType): {
    reminder: null;
} | {
    mail: null;
} | {
    message: null;
} {
    return value == NotificationType.reminder ? {
        reminder: null
    } : value == NotificationType.mail ? {
        mail: null
    } : value == NotificationType.message ? {
        message: null
    } : value;
}
function to_candid_variant_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == Priority.low ? {
        low: null
    } : value == Priority.high ? {
        high: null
    } : value == Priority.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "createNotification";
    createNotification: Notification;
} | {
    __kind__: "createTask";
    createTask: Task;
} | {
    __kind__: "createMeeting";
    createMeeting: Meeting;
} | {
    __kind__: "createAppointment";
    createAppointment: Appointment;
} | {
    __kind__: "createReminder";
    createReminder: Reminder;
}): {
    createNotification: _Notification;
} | {
    createTask: _Task;
} | {
    createMeeting: _Meeting;
} | {
    createAppointment: _Appointment;
} | {
    createReminder: _Reminder;
} {
    return value.__kind__ === "createNotification" ? {
        createNotification: to_candid_Notification_n13(uploadFile, downloadFile, value.createNotification)
    } : value.__kind__ === "createTask" ? {
        createTask: to_candid_Task_n17(uploadFile, downloadFile, value.createTask)
    } : value.__kind__ === "createMeeting" ? {
        createMeeting: to_candid_Meeting_n11(uploadFile, downloadFile, value.createMeeting)
    } : value.__kind__ === "createAppointment" ? {
        createAppointment: to_candid_Appointment_n3(uploadFile, downloadFile, value.createAppointment)
    } : value.__kind__ === "createReminder" ? {
        createReminder: value.createReminder
    } : value;
}
function to_candid_variant_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "taskCompleted";
    taskCompleted: string;
} | {
    __kind__: "meetingEnded";
    meetingEnded: string;
} | {
    __kind__: "clientCreated";
    clientCreated: string;
}): {
    taskCompleted: string;
} | {
    meetingEnded: string;
} | {
    clientCreated: string;
} {
    return value.__kind__ === "taskCompleted" ? {
        taskCompleted: value.taskCompleted
    } : value.__kind__ === "meetingEnded" ? {
        meetingEnded: value.meetingEnded
    } : value.__kind__ === "clientCreated" ? {
        clientCreated: value.clientCreated
    } : value;
}
function to_candid_variant_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppointmentStatus): {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
} {
    return value == AppointmentStatus.pending ? {
        pending: null
    } : value == AppointmentStatus.completed ? {
        completed: null
    } : value == AppointmentStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n74(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AutomationStatus): {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
} | {
    failed: null;
} {
    return value == AutomationStatus.pending ? {
        pending: null
    } : value == AutomationStatus.completed ? {
        completed: null
    } : value == AutomationStatus.inProgress ? {
        inProgress: null
    } : value == AutomationStatus.failed ? {
        failed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
